apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  APP_NAME: Laravel
  APP_ENV: local
  APP_DEBUG: "true"
  APP_TIMEZONE: UTC
  APP_URL: http://realtime-chatapp.com
  APP_LOCALE: en
  APP_FALLBACK_LOCALE: en
  APP_FAKER_LOCALE: en_US
  APP_MAINTENANCE_DRIVER: file
  PHP_CLI_SERVER_WORKERS: "4"
  BCRYPT_ROUNDS: "12"
  LOG_CHANNEL: stack
  LOG_STACK: single
  LOG_DEPRECATIONS_CHANNEL: null
  LOG_LEVEL: debug
  SESSION_DRIVER: database
  SESSION_LIFETIME: "120"
  SESSION_ENCRYPT: "false"
  SESSION_PATH: /
  SESSION_DOMAIN: null
  BROADCAST_CONNECTION: reverb
  FILESYSTEM_DISK: local
  QUEUE_CONNECTION: database
  CACHE_STORE: database
  CACHE_PREFIX: ""
  MEMCACHED_HOST: 127.0.0.1
  REDIS_CLIENT: phpredis
  REDIS_HOST: 127.0.0.1
  REDIS_PASSWORD: null
  REDIS_PORT: "6379"
  MAIL_MAILER: log
  MAIL_HOST: 127.0.0.1
  MAIL_PORT: "2525"
  MAIL_USERNAME: null
  MAIL_PASSWORD: null
  MAIL_ENCRYPTION: null
  MAIL_FROM_ADDRESS: hello@example.com
  MAIL_FROM_NAME: Laravel
  AWS_DEFAULT_REGION: us-east-1
  AWS_BUCKET: ""
  AWS_USE_PATH_STYLE_ENDPOINT: "false"
  VITE_APP_NAME: Laravel
  REVERB_APP_ID: "1410"
  REVERB_HOST: reverb
  REVERB_PORT: "8080"
  REVERB_SCHEME: http
  VITE_REVERB_APP_KEY: my-app-key
  VITE_REVERB_HOST: http://realtime-chatapp.com
  VITE_REVERB_PORT: "80"
  VITE_REVERB_SCHEME: http
  VITE_REVERB_PATH: /reverb
  APP_CONFETTI_WORDS: "chuc mung|congratulations|congrats|happy new year"
