on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      region:
        required: true
        type: string
      service:
        required: true
        type: string

name: Deploy EKS

jobs:
  notify-start:
    name: Start deploy
    runs-on: ubuntu-22.04
    environment: ${{ inputs.env }}
    steps:
      - name: Notify success
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.slack_webhook_url }}
          SLACK_CHANNEL: ${{ secrets.slack_channel_id }}
          SLACK_TITLE: Start deploy ${{ inputs.service }}-${{ inputs.env }}
          SLACK_COLOR: "#1b55de"
  
  scan-code:
    name: Snyk SCA
    runs-on: ubuntu-22.04
    needs: notify-start
    permissions:
      security-events: write
      contents: read
    environment: ${{ inputs.env }}
    steps:
      - uses: actions/checkout@v4
      - name: Snyk scan
        uses: snyk/actions/php@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
      - name: Upload results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif

  build-push:
    name: Build & Push
    runs-on: ubuntu-22.04
    needs: scan-code
    permissions:
      id-token: write
      contents: read
    environment: ${{ inputs.env }}
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          role-to-assume: ${{ secrets.ROLE_ARN }}
          aws-region: ${{ inputs.region }}
      - name: Get tag
        id: tag
        run: echo "tag=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT
      - name: ECR login
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ secrets.account_id }}.dkr.ecr.${{ inputs.region }}.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:${{ steps.tag.outputs.tag }}
            ${{ secrets.account_id }}.dkr.ecr.${{ inputs.region }}.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:latest
          build-args: |
            VITE_REVERB_APP_KEY=${{ secrets.VITE_REVERB_APP_KEY }}
            VITE_REVERB_HOST=${{ secrets.VITE_REVERB_HOST }}
            VITE_REVERB_PORT=${{ secrets.VITE_REVERB_PORT }}
            VITE_REVERB_SCHEME=${{ secrets.VITE_REVERB_SCHEME }}
            VITE_REVERB_PATH=${{ secrets.VITE_REVERB_PATH }}

  image-scan:
    name: Trivy Image Scan
    runs-on: ubuntu-22.04
    needs: build-push
    permissions:
      id-token: write
      contents: read
      security-events: write
    environment: ${{ inputs.env }}
    steps:
      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          role-to-assume: ${{ secrets.ROLE_ARN }}
          aws-region: ${{ inputs.region }}
      - name: ECR login
        uses: aws-actions/amazon-ecr-login@v2
      - name: Trivy scan
        uses: aquasecurity/trivy-action@0.30.0
        with:
          image-ref: ${{ secrets.account_id }}.dkr.ecr.${{ inputs.region }}.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:${{ needs.build-push.outputs.tag }}
          format: sarif
          output: trivy-results.sarif
      - name: Upload results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif

  update-image-tags:
    name: Update Image Tags
    runs-on: ubuntu-22.04
    needs: [scan-code, build-push, image-scan]
    environment: ${{ inputs.env }}
    steps:
      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: tanphanhue123/gitops-chatapp
          token: ${{ secrets.GITOPS_REPO_TOKEN }}
      - name: Update tags
        run: |
          TAG=${{ needs.build-push.outputs.tag }}
          ENV=${{ inputs.env }}
          
          for dir in $(ls -d helm-chart/*/ | cut -d'/' -f2 | grep -v "database"); do
            if [ -f "helm-chart/${dir}/values-${ENV}.yaml" ]; then
              sed -i "s/tag:.*$/tag: \"${TAG}\"/" "helm-chart/${dir}/values-${ENV}.yaml"
            fi
          done
          
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          
          if [[ -n $(git status -s) ]]; then
            git add .
            git commit -m "Update tag to ${TAG} for ${ENV}"
            git push
          fi
  
  # DAST:
  #   runs-on: ubuntu-22.04
  #   name: OWASP DAST
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: OWASP Scan
  #       uses: zaproxy/action-baseline@v0.14.0
  #       with:
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #         docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
  #         target: 'https://tanphanhue.shop'
  #         cmd_options: '-a'

  notify-end:
    name: Finish deploy
    runs-on: ubuntu-22.04
    if: always()
    needs: [notify-start, scan-code, build-push, image-scan, update-image-tags]
    environment: ${{ inputs.env }}
    steps:
      - name: Notify success
        if: ${{ !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') }} 
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.slack_webhook_url }}
          SLACK_CHANNEL: ${{ secrets.slack_channel_id }}
          SLACK_TITLE: Deploy ${{ inputs.service }}-${{ inputs.env }} succeeded
          SLACK_COLOR: "#00ff00"
      
      - name: Notify failure
        if: ${{ contains(needs.*.result, 'failure') }} 
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.slack_webhook_url }}
          SLACK_CHANNEL: ${{ secrets.slack_channel_id }}
          SLACK_TITLE: Deploy ${{ inputs.service }}-${{ inputs.env }} failed
          SLACK_COLOR: "#e80909"
      
      - name: Notify cancelled
        if: ${{ contains(needs.*.result, 'cancelled') }} 
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.slack_webhook_url }}
          SLACK_CHANNEL: ${{ secrets.slack_channel_id }}
          SLACK_TITLE: Deploy ${{ inputs.service }}-${{ inputs.env }} cancelled
          SLACK_COLOR: "#fae102"
